# Generated by Django 5.0 on 2024-08-28 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='PREFIXO')),
            ],
            options={
                'verbose_name': 'Equipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='TIPO')),
            ],
            options={
                'verbose_name': 'Tipo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('installment', models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Parcelamento')),
                ('first_service', models.BooleanField(editable=False, verbose_name='Primeiro Atendimento')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.team', verbose_name='Equipe')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'ordering': ['-timestamp'],
            },
        ),
    ]
