# Generated by Django 5.0 on 2024-08-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_service_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='first_service',
            field=models.BooleanField(default=False, editable=False, verbose_name='Primeiro Atendimento'),
        ),
    ]
