# Generated by Django 5.0 on 2024-08-29 01:17

import django.core.validators
import django.db.models.deletion
import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_service_first_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'O campo deve conter apenas números.')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(default=register.models.get_default_service_type, on_delete=django.db.models.deletion.CASCADE, to='register.type', verbose_name='Tipo'),
        ),
    ]
