# Generated by Django 5.0 on 2024-08-29 15:43

import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_service_number_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='timestamp',
            field=models.DateTimeField(default=register.models.diminuir_hora, verbose_name='Data e Hora'),
        ),
    ]
